# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('imagem', models.URLField(verbose_name='imagem')),
                ('bairro', models.CharField(max_length=255, verbose_name='bairro')),
                ('cep', models.CharField(max_length=8, verbose_name='cep')),
                ('cidade', models.CharField(max_length=255, verbose_name='cidade')),
                ('end', models.CharField(max_length=255, verbose_name='end')),
                ('uf', models.CharField(max_length=2, verbose_name='uf')),
            ],
            options={
                'verbose_name': 'imovel',
                'verbose_name_plural': 'imoveis',
            },
        ),
    ]
