# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-22 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='valor',
            field=models.FloatField(default=0, verbose_name='valor'),
        ),
    ]
