# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-22 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_imovel_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='valor',
            field=models.FloatField(blank=True, default=0, verbose_name='valor'),
        ),
    ]
